[package]
name = "rcpt"
version = "0.1.0"
authors = ["Peter McEvoy <peter.michael.mcevoy@gmail.com>"]
edition = "2018"

[dependencies]
lodepng = "*"
rand = "*"
rayon = "1.5.1"
num = "*"
lazy_static = "1.3.0"

[features]
use_sampled_spectrum = []
