[package]
name = "rcpt"
version = "0.1.0"
authors = ["Peter McEvoy <peter.michael.mcevoy@gmail.com>"]
edition = "2018"

[dependencies]
lodepng = "*"
rand = "*"
rayon = "*"
nalgebra = "0.18.0"

[features]
real_is_double = []
